### ISSUE TITLE
Not clear how action function trigger store functons

### ISSUE THREAD

**Issue by jlmitch5** [limelights/todo-reflux#10]
I just implemented a delete-all route for your example (thanks for this by the way).  I'm a little confused as to how the action functions trigger the store functions.

for example the action `removeTodo`:
```
TodoActions.removeTodo.preEmit = function (id) {
    request.del('/todo/'+id+'/', function () {});
};
```

eventually triggers the store function `onRemoveTodo`:
```
onRemoveTodo: function (key) {
        var list = _.reject(this.list, function (item) {
            return item.key === key;
        });

        if (_.isEmpty(list)) {
            this.todoCounter = 1;
        }

        this.updateList(list);
    }
```

But like...how?  I see this thing in the docs of todo_item:  `* @removeTodo TodoActions#removeTodo->#onRemoveTodo`, but I've ruled out the docs setting up this binding.  So, what is?

**Comment by jlmitch5** [comment]
Here's my code for the delete-all if you'd like to see it by the way.  This was for my own edification, but I'm happy to PR it if you want it.

**Comment by limelights** [comment]
Thanks for this, PR is absolutely welcome (just add a test for it and you're good to go).

Great question, the magic is performed by Reflux itself, so I perse haven't implemented any thing that connects an action to a store.
However, this is how it works;

The magic happens on this line https://github.com/limelights/todo-reflux/blob/master/app/javascript/src/todo_store.js#L16 , when this gets run Reflux will setup a listener on all of the functors inside your actions `TodoActions` which maps back to a function that has the signature `on<ActionName>`. Code responsible for this is;

https://github.com/spoike/refluxjs/blob/169d27688572fc31cc200be91683b73fa5899289/src/ListenerMethods.js

Hope it makes it a bit clearer! :)

**Comment by limelights** [comment]
Closing this issue as it seems to have been answered!
