### ISSUE TITLE
Compile with lessc fails

### ISSUE THREAD

**Issue by jefffranks** [limelights/todo-reflux#11]
The compile step with lessc failed with the following error:

$ lessc app/less/styles.less app/static/css/styles.css
jfranks@jlf-mint-17 ~/Desktop/reflux validate/todo-reflux-master $ lessc app/less/styles.less app/static/css/styles.css
ParseError: Unrecognised input in /home/jfranks/Desktop/reflux validate/todo-reflux-master/app/less/mixins.less on line 21, column 9:
20     @media screen and (max-width: 480px) {
21         @rules();
22     }

Host environment is Linux Mint 17.1.

$ lessc --version
lessc 1.4.2 (LESS Compiler) [JavaScript]

All of the steps preceding this went well, the application ran in the browser, the tests passed.

Please let me know if I can be of further help on this.

--jlf

**Comment by limelights** [comment]
Hej @jefffranks!

Have you tried updating LESS to the latest version? Project was built on `2.3.1`.
Let me know if upgrading helps otherwise I'll get cracking on help you! :)

**Comment by jefffranks** [comment]
Henrick,

The issue is RESOLVED upon updating LESS to the latest version.

$ lessc --version
lessc 2.5.0 (Less Compiler) [JavaScript]

My lesson learned is that this development domain is moving too fast to be accomodated by a native package manager that comes with the distribution -- Linux Mint Rebecca + Synaptic in this case. The packages that are provided are already too dated and incompatible.

This might be a heads up for other developers.

Thank you for your help and direction.

regards,
Jeff Franks

**Comment by limelights** [comment]
Excellent! :)
Glad you got it working and if you need any more help with whatever just raise an issue here and I'll get to it! :)
