### ISSUE TITLE
Document the suggested way to compile jsx

### ISSUE THREAD

**Issue by andybak** [limelights/todo-reflux#9]
I'm guessing webpack handles this but I've never used it so it will take a bit of fiddling to make sure.

Same way you say 'to compile the .less type xyz' - could you also document the preferred way to compile the jsx?

**Comment by limelights** [comment]
Webpack handles this for us, which it does through the Loaders in `webpack.config.js`.

**Comment by andybak** [comment]
In that case I must be doing something wrong. The simple test I did was:

1. Edit the <h1> text in todo_container.jsx
2. python runserver.py
3. The page still shows the old h1

**Comment by limelights** [comment]
You certainly didn't do anything wrong but you most likely didn't run webpack with the `--watch` flag in order for webpack to be notified of file changes.

**Comment by andybak** [comment]
Ah! That's the exact thing I was asking to be added to the documentation. It doesn't say that anywhere. When you said "Webpack handles this for us" above I thought you were saying "it happens by magic". ;-)

So I installed webpack via npm and tried running it but I get:

    ERROR in Entry module not found: Error: Cannot resolve module 'jsxhint-loader' in /path/to/reflux/todo-reflux

**Comment by limelights** [comment]
I see, I've added it to the documentation. If you run `npm install` within the project you'll install all of the dependencies you need in order for you to be able to run the project.

**Comment by andybak** [comment]
Thanks! Maybe also add 'npm install' to the docs.
